<a href="https://colab.research.google.com/github/ClaudioSeveroo/ciencia_de_dados/blob/main/exercicio_pcd10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Dados iniciais
dados = np.array([
    [120, 15000, 100, 125.00, 4],
    [135, 16200, 108, 120.00, 5],
    [98, 11700, 82, 119.39, 3],
    [150, 21000, 125, 140.00, 7],
    [175, 24500, 140, 140.00, 9],
    [160, 22400, 132, 140.00, 6],
    [110, 13200, 95, 120.00, 2]
])

dias = np.array([
    "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"
])

In [3]:
print("--- Parte 1 ---")
print("1.1 Linhas:", dados.shape[0])
print("1.1 Colunas:", dados.shape[1])
print("1.1 Total de valores:", dados.size)
print("1.1 Dimensões:", dados.ndim)
print("1.1 Tipo dos dados:", dados.dtype)
print("\n")

--- Parte 1 ---
1.1 Linhas: 7
1.1 Colunas: 5
1.1 Total de valores: 35
1.1 Dimensões: 2
1.1 Tipo dos dados: float64




In [4]:
print("--- Parte 2 ---")
print("2.1 Dados de sexta-feira:", dados[4])
print("2.2 Somente faturamento:", dados[:, 1])
print("2.3 Somente reclamações:", dados[:, 4])
print("2.4 Quinta até domingo:\n", dados[3:])
print("2.5 Pedidos, faturamento e clientes:\n", dados[:, 0:3])
print("\n")

--- Parte 2 ---
2.1 Dados de sexta-feira: [1.75e+02 2.45e+04 1.40e+02 1.40e+02 9.00e+00]
2.2 Somente faturamento: [15000. 16200. 11700. 21000. 24500. 22400. 13200.]
2.3 Somente reclamações: [4. 5. 3. 7. 9. 6. 2.]
2.4 Quinta até domingo:
 [[1.50e+02 2.10e+04 1.25e+02 1.40e+02 7.00e+00]
 [1.75e+02 2.45e+04 1.40e+02 1.40e+02 9.00e+00]
 [1.60e+02 2.24e+04 1.32e+02 1.40e+02 6.00e+00]
 [1.10e+02 1.32e+04 9.50e+01 1.20e+02 2.00e+00]]
2.5 Pedidos, faturamento e clientes:
 [[  120. 15000.   100.]
 [  135. 16200.   108.]
 [   98. 11700.    82.]
 [  150. 21000.   125.]
 [  175. 24500.   140.]
 [  160. 22400.   132.]
 [  110. 13200.    95.]]




In [5]:
print("--- Parte 3 ---")
print("3.1 Total de pedidos:", np.sum(dados[:, 0]))
print("3.2 Faturamento total:", np.sum(dados[:, 1]))
print("3.3 Total de clientes:", np.sum(dados[:, 2]))
print("3.4 Média de pedidos:", np.mean(dados[:, 0]))
print("3.5 Média de faturamento:", np.mean(dados[:, 1]))
print("3.6 Média de reclamações:", np.mean(dados[:, 4]))
print("\n")

--- Parte 3 ---
3.1 Total de pedidos: 948.0
3.2 Faturamento total: 124000.0
3.3 Total de clientes: 782.0
3.4 Média de pedidos: 135.42857142857142
3.5 Média de faturamento: 17714.285714285714
3.6 Média de reclamações: 5.142857142857143




In [6]:
print("--- Parte 4 ---")
pos_maior_pedido = np.argmax(dados[:, 0])
pos_menor_pedido = np.argmin(dados[:, 0])
print("4.1 Maior número de pedidos:", dias[pos_maior_pedido])
print("4.1 Menor número de pedidos:", dias[pos_menor_pedido])

pos_maior_fat = np.argmax(dados[:, 1])
pos_menor_fat = np.argmin(dados[:, 1])
print("4.2 Maior faturamento:", dias[pos_maior_fat])
print("4.2 Menor faturamento:", dias[pos_menor_fat])

amplitude = np.max(dados[:, 1]) - np.min(dados[:, 1])
print("4.3 Amplitude do faturamento:", amplitude)
print("\n")

--- Parte 4 ---
4.1 Maior número de pedidos: Sexta
4.1 Menor número de pedidos: Quarta
4.2 Maior faturamento: Sexta
4.2 Menor faturamento: Quarta
4.3 Amplitude do faturamento: 12800.0




In [7]:
print("--- Parte 5 ---")
# Usei os valores 20000, 150 e 5 para completar os espaços em branco do exercício
mascara_fat = dados[:, 1] > 20000
print("5.1 Faturamento superior a 20.000:", dias[mascara_fat])

mascara_pedidos = dados[:, 0] > 150
print("5.2 Mais de 150 pedidos:", dias[mascara_pedidos])

mascara_reclamacoes = dados[:, 4] > 5
print("5.3 Mais de 5 reclamações:", dias[mascara_reclamacoes])

print("5.4 Faturamentos com mais de 150 pedidos:", dados[mascara_pedidos, 1])

media_semana = np.mean(dados[:, 1])
mascara_abaixo_media = dados[:, 1] < media_semana
print("5.5 Dias com faturamento abaixo da média:", np.sum(mascara_abaixo_media))
print("\n")

--- Parte 5 ---
5.1 Faturamento superior a 20.000: ['Quinta' 'Sexta' 'Sábado']
5.2 Mais de 150 pedidos: ['Sexta' 'Sábado']
5.3 Mais de 5 reclamações: ['Quinta' 'Sexta' 'Sábado']
5.4 Faturamentos com mais de 150 pedidos: [24500. 22400.]
5.5 Dias com faturamento abaixo da média: 4




In [8]:
print("--- Parte 6 ---")
classificacao = np.where(dados[:, 1] >= 20000, "Alto desempenho", "Desempenho normal")
print("6.1 Classificação dos dias:\n", classificacao)

dias_alto_desempenho = np.sum(classificacao == "Alto desempenho")
print("6.2 Quantos dias de alto desempenho:", dias_alto_desempenho)
print("\n")

--- Parte 6 ---
6.1 Classificação dos dias:
 ['Desempenho normal' 'Desempenho normal' 'Desempenho normal'
 'Alto desempenho' 'Alto desempenho' 'Alto desempenho' 'Desempenho normal']
6.2 Quantos dias de alto desempenho: 3




In [9]:
print("--- Parte 7 ---")
fat = dados[:, 1]
print("Média:", np.mean(fat))
print("Mediana:", np.median(fat))
print("Desvio padrão:", np.std(fat))
print("Mínimo:", np.min(fat))
print("Máximo:", np.max(fat))
print("O faturamento apresenta grande variação? Sim, o desvio padrão é muito alto (mais de 4500) e a diferença entre o mínimo (11700) e o máximo (24500) é enorme.")
print("\n")

--- Parte 7 ---
Média: 17714.285714285714
Mediana: 16200.0
Desvio padrão: 4551.429468209041
Mínimo: 11700.0
Máximo: 24500.0
O faturamento apresenta grande variação? Sim, o desvio padrão é muito alto (mais de 4500) e a diferença entre o mínimo (11700) e o máximo (24500) é enorme.




In [10]:
print("--- Parte 8 ---")
print("8.1 Média por indicador:", np.mean(dados, axis=0))
print("8.2 Maior valor por indicador:", np.max(dados, axis=0))
print("8.3 Menor valor por indicador:", np.min(dados, axis=0))
print("8.4 Comparando os resultados, as Reclamações têm a maior variação relativa, porque elas vão de 2 até 9 (cresce mais de 4 vezes), enquanto os outros números não sobem tanto assim proporcionalmente.")
print("\n")

--- Parte 8 ---
8.1 Média por indicador: [1.35428571e+02 1.77142857e+04 1.11714286e+02 1.29198571e+02
 5.14285714e+00]
8.2 Maior valor por indicador: [1.75e+02 2.45e+04 1.40e+02 1.40e+02 9.00e+00]
8.3 Menor valor por indicador: [9.8000e+01 1.1700e+04 8.2000e+01 1.1939e+02 2.0000e+00]
8.4 Comparando os resultados, as Reclamações têm a maior variação relativa, porque elas vão de 2 até 9 (cresce mais de 4 vezes), enquanto os outros números não sobem tanto assim proporcionalmente.




In [11]:
print("--- Parte 9 ---")
dia_melhor_fat = dias[np.argmax(dados[:, 1])]
print("9.1 Melhor dia em faturamento:", dia_melhor_fat)

dia_mais_pedidos = dias[np.argmax(dados[:, 0])]
print("9.2 Tem a maior quantidade de pedidos?")
if dia_melhor_fat == dia_mais_pedidos:
    print("Sim")
else:
    print("Não")

dia_mais_reclamacoes = dias[np.argmax(dados[:, 4])]
print("9.3 Tem o maior número de reclamações?")
if dia_melhor_fat == dia_mais_reclamacoes:
    print("Sim")
else:
    print("Não")

filtro_dois = (dados[:, 0] > 150) & (dados[:, 1] > 20000)
print("9.4 Dias com +150 pedidos e fat > 20000:", np.sum(filtro_dois))
print("\n")

--- Parte 9 ---
9.1 Melhor dia em faturamento: Sexta
9.2 Tem a maior quantidade de pedidos?
Sim
9.3 Tem o maior número de reclamações?
Sim
9.4 Dias com +150 pedidos e fat > 20000: 2




In [12]:
print("--- Parte 10 ---")
print("RESUMO DA SEMANA")
print("Total de pedidos:", np.sum(dados[:, 0]))
print("Faturamento total:", np.sum(dados[:, 1]))
print("Média diária de pedidos:", np.mean(dados[:, 0]))
print("Média diária de faturamento:", np.mean(dados[:, 1]))
print("Melhor dia:", dias[np.argmax(dados[:, 1])])
print("Pior dia:", dias[np.argmin(dados[:, 1])])
print("Maior número de reclamações:", np.max(dados[:, 4]))
print("Dias de alto desempenho:", np.sum(dados[:, 1] >= 20000))

--- Parte 10 ---
RESUMO DA SEMANA
Total de pedidos: 948.0
Faturamento total: 124000.0
Média diária de pedidos: 135.42857142857142
Média diária de faturamento: 17714.285714285714
Melhor dia: Sexta
Pior dia: Quarta
Maior número de reclamações: 9.0
Dias de alto desempenho: 3


In [14]:
#Parte 11 — Conclusão

#O desempenho da empresa na semana foi bom no final de semana, mas muito fraco no meio. A sexta-feira foi
# o melhor dia de todos, onde a empresa vendeu mais e teve o maior faturamento (R$ 24.500,00). O dia que
# merece atenção urgente é a quarta-feira, que foi o pior dia da semana e vendeu muito pouco.

#Olhando para os números, existe uma relação clara entre os pedidos, o faturamento e as reclamações.
#Na sexta-feira, que foi o dia com mais pedidos e mais faturamento, também foi o dia com o maior número de reclamações, no caso 9.
# Isso mostra que quando a loja vende muito, a equipe não consegue dar conta e os clientes acabam reclamando mais.